export type FsmStateName =
  | 'ANCHOR_PAGE'
  | 'STATE_SELECTION'
  | 'CITY_SELECTION'
  | 'STORE_SELECTION'
  | 'LEAFLETS_PAGE'
  | 'LEAFLET_MODAL'
  | 'PDF_DOWNLOAD'
  | 'IMAGE_GALLERY'
  | 'ERROR_RECOVERY';
