import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      exclude: [
        'coverage/**',
        'dist/**',
        'dist-ssr/**',
        'node_modules/**',
        'src/application/ports/**',
        'src/**/*.d.ts',
        'src/App.tsx',
        'src/domain/dataset/visual-dataset-sample.ts',
        'src/domain/dataset/dataset-split.ts',
        'src/domain/dataset/screenshot-metadata.ts',
        'src/domain/dataset/target-semantic-label.ts',
        'src/domain/extraction/extraction-run-status.ts',
        'src/domain/extraction/extraction-run.ts',
        'src/domain/extraction/fsm-state-name.ts',
        'src/domain/leaflet/**',
        'src/domain/supermarket/**',
        'src/domain/visual/capture-artifact.ts',
        'src/domain/visual/capture-result.ts',
        'src/infrastructure/playwright/visual-browser.ts',
        'src/infrastructure/playwright/playwright-visual-dataset-page.ts',
        'src/infrastructure/scrapers/carnauba/carnauba-api-types.ts',
        'src/infrastructure/scrapers/carnauba/carnauba-leaflet-page.ts',
        'src/infrastructure/scrapers/carnauba/playwright-carnauba-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/carnauba/playwright-mercadapp-auth-token-provider.ts',
        'src/infrastructure/storage/fetch-leaflet-image-http-client.ts',
        'src/infrastructure/worker/carnauba-api-extract-command.ts',
        'src/infrastructure/worker/carnauba-leaflets-smoke-command.ts',
        'src/infrastructure/worker/carnauba-playwright-command.ts',
        'src/infrastructure/worker/visual-dataset-validate-command.ts',
        'src/infrastructure/worker/visual-capture-smoke-command.ts',
        'src/main.tsx',
        'src/worker-main.ts',
      ],
      include: ['src/**/*.{ts,tsx}'],
      provider: 'v8',
      reporter: ['text', 'lcov'],
      thresholds: {
        branches: 100,
        functions: 100,
        lines: 100,
        statements: 100,
      },
    },
    environment: 'node',
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'src/**/*.spec.ts',
      'src/**/*.spec.tsx',
      'tests/**/*.test.ts',
      'tests/**/*.test.tsx',
      'tests/**/*.spec.ts',
      'tests/**/*.spec.tsx',
    ],
    passWithNoTests: false,
  },
});
