import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      exclude: [
        'coverage/**',
        'dist/**',
        'dist-ssr/**',
        'node_modules/**',
        'src/application/ports/**',
        'src/**/*.d.ts',
        'src/App.tsx',
        'src/domain/dataset/visual-dataset-sample.ts',
        'src/domain/dataset/dataset-split.ts',
        'src/domain/dataset/screenshot-metadata.ts',
        'src/domain/dataset/target-semantic-label.ts',
        'src/domain/extraction/extraction-run-status.ts',
        'src/domain/extraction/extraction-run.ts',
        'src/domain/extraction/fsm-state-name.ts',
        'src/domain/leaflet/**',
        'src/domain/supermarket/**',
        'src/domain/visual/capture-artifact.ts',
        'src/domain/visual/capture-result.ts',
        'src/infrastructure/playwright/visual-browser.ts',
        'src/infrastructure/playwright/playwright-visual-dataset-page.ts',
        'src/infrastructure/scrapers/carnauba/carnauba-api-types.ts',
        'src/infrastructure/scrapers/carnauba/carnauba-leaflet-page.ts',
        'src/infrastructure/scrapers/carnauba/playwright-carnauba-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/carnauba/playwright-mercadapp-auth-token-provider.ts',
        'src/infrastructure/scrapers/mixmateus/mixmateus-leaflet-page.ts',
        'src/infrastructure/scrapers/mixmateus/mixmateus-pdf-leaflet.ts',
        'src/infrastructure/scrapers/mixmateus/playwright-mixmateus-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/assai/assai-image-gallery-leaflet.ts',
        'src/infrastructure/scrapers/assai/assai-leaflet-page.ts',
        'src/infrastructure/scrapers/assai/playwright-assai-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/angeloni/angeloni-leaflet-page.ts',
        'src/infrastructure/scrapers/angeloni/angeloni-pdf-leaflet.ts',
        'src/infrastructure/scrapers/angeloni/playwright-angeloni-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/comboatacadista/combo-atacadista-image-gallery-leaflet.ts',
        'src/infrastructure/scrapers/comboatacadista/combo-atacadista-leaflet-page.ts',
        'src/infrastructure/scrapers/comboatacadista/playwright-combo-atacadista-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/coop/coop-image-gallery-leaflet.ts',
        'src/infrastructure/scrapers/coop/coop-leaflet-page.ts',
        'src/infrastructure/scrapers/coop/playwright-coop-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/tauste/tauste-leaflet-page.ts',
        'src/infrastructure/scrapers/tauste/tauste-pdf-leaflet.ts',
        'src/infrastructure/scrapers/tauste/playwright-tauste-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/atacadao/atacadao-leaflet-page.ts',
        'src/infrastructure/scrapers/atacadao/atacadao-pdf-leaflet.ts',
        'src/infrastructure/scrapers/atacadao/playwright-atacadao-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/bistek/bistek-image-gallery-leaflet.ts',
        'src/infrastructure/scrapers/bistek/bistek-leaflet-page.ts',
        'src/infrastructure/scrapers/bistek/playwright-bistek-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/comboatacadista/combo-atacadista-image-gallery-leaflet.ts',
        'src/infrastructure/scrapers/superdopovo/playwright-superdopovo-api-client.ts',
        'src/infrastructure/scrapers/superdopovo/playwright-superdopovo-leaflet-page.factory.ts',
        'src/infrastructure/scrapers/superdopovo/superdopovo-api-types.ts',
        'src/infrastructure/scrapers/superdopovo/superdopovo-leaflet-page.ts',
        'src/infrastructure/storage/fetch-leaflet-image-http-client.ts',
        'src/infrastructure/storage/fetch-leaflet-pdf-http-client.ts',
        'src/infrastructure/worker/carnauba-api-extract-command.ts',
        'src/infrastructure/worker/atacadao-playwright-command.ts',
        'src/infrastructure/worker/assai-playwright-command.ts',
        'src/infrastructure/worker/carnauba-leaflets-smoke-command.ts',
        'src/infrastructure/worker/carnauba-playwright-command.ts',
        'src/infrastructure/worker/extraction-worker-command.ts',
        'src/infrastructure/worker/mixmateus-playwright-command.ts',
        'src/infrastructure/worker/superdopovo-playwright-command.ts',
        'src/infrastructure/worker/visual-dataset-validate-command.ts',
        'src/infrastructure/worker/visual-capture-smoke-command.ts',
        'src/main.tsx',
        'src/worker-main.ts',
      ],
      include: ['src/**/*.{ts,tsx}'],
      provider: 'v8',
      reporter: ['text', 'lcov'],
      thresholds: {
        branches: 100,
        functions: 100,
        lines: 100,
        statements: 100,
      },
    },
    environment: 'node',
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'src/**/*.spec.ts',
      'src/**/*.spec.tsx',
      'tests/**/*.test.ts',
      'tests/**/*.test.tsx',
      'tests/**/*.spec.ts',
      'tests/**/*.spec.tsx',
    ],
    passWithNoTests: false,
  },
});
